name: Deploy to EC2

on:
  push:
    branches:
      - master   # Change this if your branch name is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Laravel App via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/ContactsAppLaravelM
            git pull origin main
            composer install --no-interaction --prefer-dist
            php artisan migrate --force
            php artisan config:cache
